/** English labels captured with the verified EPİAŞ electricity menu snapshot. */
export const VERIFIED_CATALOG_ENGLISH_LABELS: Readonly<Record<number, string>> = Object.freeze({
  36: "Maximum Settlement Price",
  40: "Licensed power-plant investments",
  49: "RSM portfolio income",
  50: "RSM imbalance cost",
  51: "RSM imbalance quantity",
  52: "WPP generation and forecast",
  54: "License-exempt feed-in amount",
  55: "License-exempt feed-in cost",
  56: "Generation forecast",
  57: "Spot order",
  58: "Unit cost",
  59: "Installed capacity",
  60: "Licensed generation feed-in cost",
  61: "RSM income",
  62: "Total cost",
  63: "RSM participant list",
  67: "Interconnection failure/maintenance",
  69: "Interconnection line capacities",
  70: "Interconnection capacity requests",
  71: "Nominal capacity",
  72: "Daily Kot",
  73: "Active fullness",
  74: "Active volume",
  75: "Daily volume",
  76: "Water energy provision",
  89: "ENTSO-E (W) codes",
  90: "MCP/SMP/imbalance listing",
  91: "Daily report",
  92: "Periodic price averages",
  93: "Periodic market volumes",
  94: "Eligible consumer/meter increases",
  95: "MCP/SMP price averages",
  96: "MCP/SMP three-time averages",
  97: "Daily prices",
  98: "Physical electricity market volumes",
  99: "BPM instructions",
  101: "IDM contract summary",
  102: "Market Clearing Price (MCP)",
  103: "Interim MCP",
  104: "DAM Trade Value",
  105: "DAM Price Independent Sales Order",
  106: "DAM Price Independent Bid Order",
  107: "DAM Supply-Demand",
  108: "DAM Submitted Bid Order Volume",
  109: "DAM Submitted Sales Order Volume",
  110: "DAM Block Bid",
  111: "DAM Block Offer",
  112: "DAM Matching Quantity",
  113: "DAM Flexible Buying Offer Quantity",
  114: "DAM Flexible Selling Offer Quantity",
  115: "DAM Matched Flexible Offer Quantity",
  116: "DAM Side Payment",
  117: "IDM Weighted Average Price",
  118: "IDM Matching Quantity",
  119: "IDM Min-Max Bid Price",
  120: "IDM Min-Max Offer Price",
  121: "IDM Min-Max Matching Price",
  122: "IDM Bid/Offer Quantities",
  123: "IDM Trade Value",
  124: "IDM Transaction History",
  125: "PFM Daily Index Price",
  126: "PFM Matching Quantity",
  127: "PFM Trade Value",
  128: "PFM Transaction History",
  129: "PFM Contract Price Summary",
  130: "PFM Open Position",
  131: "PFM Order Prices",
  132: "System Marginal Price",
  133: "System Direction",
  134: "Up Regulation Instructions",
  135: "Down Regulation Instructions",
  136: "Issued YEK-G documents",
  137: "YEK-G expiry quantity",
  138: "YEK-G withdrawal quantity",
  139: "YEK-G bilateral contracts",
  140: "YEK-G redemption quantity",
  141: "YEK-G weighted average price",
  142: "YEK-G matching quantity",
  143: "YEK-G min/max matching price",
  144: "YEK-G organized-market trading volume",
  145: "YEK-G organized-market bid/ask",
  146: "Primary frequency capacity price",
  147: "Primary frequency capacity amount",
  148: "Secondary frequency capacity price",
  149: "Secondary frequency capacity amount",
  150: "Bilateral contracts bid quantity",
  151: "Bilateral contracts offer quantity",
  152: "EÜAŞ-authorized retailers bilateral amount",
  153: "Imbalance quantity",
  154: "Imbalance cost",
  155: "Balance Responsible Group imbalance",
  156: "Meter count subject to retroactive adjustment",
  157: "Retroactive adjustment sum",
  158: "Meter volume subject to retroactive adjustment",
  159: "Participant count by license type",
  160: "Market participants",
  161: "FDPP",
  162: "SBFGP",
  163: "AIC",
  164: "Real-time generation",
  165: "Injection quantity",
  166: "Load forecast plan",
  167: "Demand forecast",
  168: "Real-time consumption",
  169: "Withdrawal quantity",
  170: "Eligible-customer withdrawal quantity",
  171: "Withdrawal under supply liability",
  172: "Percentage consumption information",
  173: "Multiple factor",
  174: "Meter count",
  175: "Eligible customer count",
  176: "Eligible customer quantity",
  177: "City/district eligible customer count",
  178: "Monthly index",
  179: "Planned outage information",
  180: "Unplanned outage information",
  181: "Consumer quantity",
  182: "Consumption quantity",
  183: "YEKDEM real-time generation",
  184: "YEKDEM injection quantity",
  185: "Monthly zero balance adjustment",
  186: "Transmission loss factor",
  187: "Congestion cost",
  188: "ENTSO-E (X) codes",
  189: "Yearly interconnection forecast",
  190: "Monthly interconnection forecast",
  191: "Dam Kot",
  192: "Dam volume",
  193: "Dam flow rate/install capacity",
  248: "Market Message System",
  253: "IDM order list",
  254: "Electricity market bulletins",
  257: "BPM weighted instructions",
  258: "FDPP first version",
});
